[package]
name = "model"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = { version = "0.6.4", default-features = false, features = ["deflate"] }
serde = { version = "1", features = ["derive"] }
quick-xml = { version = "0.29.0", features = ["serialize"] }
